$(document).ready(function(){var a=0;$("#next").click(function(){var b=$(".activeInstruction");b.removeClass("activeInstruction").addClass("hidden");b.next().addClass("activeInstruction").removeClass("hidden");a++;4===a&&skipToStart()});$("#skip").click(skipToStart)});
var skipToStart=function(){$(".activeInstruction").fadeOut("500").removeClass("activeInstruction");$("#welcome").fadeOut("500");$("#game").fadeIn("500").addClass("active").removeClass("hidden");initializeGame()},cpuFacedown,playerFacedown,cpuHand,playerHand,playerFaceup,cpuFaceup,deck,pile,initializeGame=function(){resetAll();for(var a=0;6>a;a++)3>a&&(cpuFacedown.push(deck.pop()),playerFacedown.push(deck.pop())),cpuHand.push(deck.pop()),playerHand.push(deck.pop());var b=0;makeCard(playerHand,"playerhand");
$(".card").unbind("click").click(function(){$(this).hasClass("selected")?($(this).removeClass("selected"),b--):($(this).addClass("selected"),b++)});$("#startGame").click(function(){if(3!=b)$("#pickAgain").fadeIn("500");else{$(this).fadeOut("500");$("#pickAgain").fadeOut("500");$(".selected > p").each(function(){var a=parseInt($(this).text());removeCard(playerHand,"playerhand",a);playerFaceup.push(a)});$(".selected").removeClass("selected");makeCard(playerFaceup,"playerfaceup");makeCard(playerFacedown,
"playerfacedown","facedown");makeCard(cpuHand,"cpuhand","facedown");for(var a=0;a<cpuHand.length;a++)if(3>a)cpuFaceup.push(cpuHand[a]);else for(var c=cpuHand[a],e=0;e<cpuFaceup.length;e++)if(0<compareCards(c,cpuFaceup[e],"cpuAI")){var f=cpuFaceup[e];cpuFaceup[e]=c;c=f}$(cpuFaceup).each(function(){removeCard(cpuHand,"cpuhand",this)});makeCard(cpuFaceup,"cpufaceup");makeCard(cpuFacedown,"cpufacedown","facedown");$(".start").fadeIn("500");$("#deck #remainingCards").text(deck.length);$("#chooseThree").fadeOut("500");
gamePlay()}})};function gamePlay(){0===Math.floor(2*Math.random())?playerTurn():cpuTurn()}
function playerTurn(){var a=[];$("#playerfacedown").off();if(0!==playerHand.length)$("#playerfaceup").off(),$("#playerhand").off(),$("#playerhand").on("dblclick",".card",function(){playerDblClick(this)}),$("#playerhand").on("click",".card",function(){a=playerClick(this,a)});else if(0!==playerFaceup.length)$(".faceupdown").css("z-index","1"),$("#playerfaceup").off(),$("#playerfaceup").on("dblclick",".card",function(){playerDblClick(this)}),$("#playerfaceup").on("click",".card",function(){a=playerClick(this,
a)});else if(0!==playerFacedown.length)$("#playerfacedown").on("dblclick",".card",function(){playerDblClick(this,FACEDOWN)});0===playerFacedown.length&&0===playerHand.length&&winScreen();$("#select").unbind("click").click(function(){0<a.length&&(console.log("player push: "+getCardValue(a[0])+" "+a.length+"x"),playCard(a,PLAYER))});$("#pickup").unbind("click").click(function(){$("#bomb").css("visibility","hidden");0!==pile.length&&pickupPile(PLAYER)})}
function cpuTurn(){0!==cpuHand.length?cpuPlayCard(cpuHand):0!==cpuFaceup.length?cpuPlayCard(cpuFaceup):0!==cpuFacedown.length&&cpuPlayFacedownCard();0===cpuFacedown.length&&0===cpuHand.length&&loseScreen()}
function cpuPlayFacedownCard(){var a=Math.floor(Math.random()*cpuFacedown.length),a=cpuFacedown[a];if(0<=compareTopCard(a)){playCard([a],1,CPU);var b=$("#cpumove").text();$("#cpumove").text(b+" "+getCardValue(a)+" (1x)")}else pile.push(a),console.log("cpu pick up pile"),removeCard(cpuFacedown,"cpufacedown",a),pickupPile(CPU)}
function cpuPlayCard(a){a.sort(function(a,b){return compareCards(a,b,"cpuAI")});for(var b=0,d,c=[],b=0;b<a.length;b++)if(d=a[b],0===pile.length||0<=compareTopCard(d)){c.push(d);break}if(1===c.length)for(var e=b+1;e<b+4&&e<a.length;e++)0===compareCards(d,a[e])&&(console.log("cpu has more than one"),c.push(a[e]));0!==c.length?(a=getCardValue(c[0]),console.log("cpu push "+a+" "+c.length+"x"),b=$("#cpumove").text(),$("#cpumove").text(b+" "+a+" ("+c.length+"x)"),playCard(c,CPU),console.log("pile: "+pile.toString())):
pickupPile(CPU)}
function playCard(a,b){var d=getCardValue(a[0]);b===PLAYER&&($("#cpumove").text(""),$("#bomb").css("visibility","hidden"));for(var c=0;c<a.length;c++)pile.push(a[c]);for(c=0;c<a.length;c++)b===PLAYER?0<playerHand.length?removeCard(playerHand,"playerhand",a[c]):0<playerFaceup.length?removeCard(playerFaceup,"playerfaceup",a[c]):removeCard(playerFacedown,"playerfacedown",a[c]):0<cpuHand.length?removeCard(cpuHand,"cpuhand",a[c]):0<cpuFaceup.length?removeCard(cpuFaceup,"cpufaceup",a[c]):removeCard(cpuFacedown,
"cpufacedown",a[c]);checkBomb()&&(d="10");c=!1;switch(d){case "10":bomb(b);c=!0;break;case "2":c=!0}3>=playerHand.length&&$("#player").css("width","300");3>=cpuHand.length&&$("#cpu").css("width","300");redoPile();drawCard(b);c?repeatTurn(b):switchTurn(b)}
function playerClick(a,b){$("#startmsg").fadeOut("500");var d=parseInt($(a).children("p").text()),c=getCardValue(d),e;0!==b.length&&(e=getCardValue(b[0]));0<=compareTopCard(d)&&(c!==e?(b=[d],$(".selected").removeClass("selected"),$(a).addClass("selected")):-1===b.indexOf(d)?($(a).addClass("selected"),b.push(d)):($(a).removeClass("selected"),d=b.indexOf(d),b.splice(d,1)));return b}var FACEDOWN=!0;
function playerDblClick(a,b){$("#startmsg").fadeOut("500");var d=parseInt($(a).children("p").text()),c=getCardValue(d);b===FACEDOWN&&($("#playerflipped").fadeIn(),$("#flipped").text(c));0===pile.length||0<=compareTopCard(d)?($(".selected").removeClass("selected"),console.log("player push: "+c+" 1x"),playCard([d],PLAYER)):b===FACEDOWN&&(pile.push(d),pickupPile(PLAYER),removeCard(playerFacedown,"playerfacedown",d))}
function compareTopCard(a){if(0===pile.length)return 1;var b=pile[pile.length-1];return"7"===getCardValue(b)?compareCards(a,b,"SEVEN"):compareCards(a,b)}function drawCard(a){0<deck.length&&(a===PLAYER?(3>playerHand.length&&(a=deck.pop(),playerHand.push(a),makeCard([a],"playerhand")),3>playerHand.length&&drawCard(PLAYER)):(3>cpuHand.length&&(a=deck.pop(),cpuHand.push(a),makeCard([a],"cpuhand","facedown")),3>cpuHand.length&&drawCard(CPU)),$("#deck #remainingCards").text(deck.length))}
function repeatTurn(a){a===PLAYER?playerTurn():cpuTurn()}function switchTurn(a){a===PLAYER?cpuTurn():playerTurn()}function checkBomb(){if(4<=pile.length){for(var a=getCardValue(pile[pile.length-1]),b=2;5>b;b++)if(a!==getCardValue(pile[pile.length-b]))return!1;console.log("four in a row");return!0}return!1}function bomb(a){console.log("bomb");pile.length=0;redoPile();$("#bomb").css("visibility","visible")}var PLAYER=!0,CPU=!1;
function pickupPile(a){a===PLAYER?($("#cpumove").text(""),makeCard(pile,"playerhand"),playerHand=playerHand.concat(pile),3<playerHand.length&&$("#player").css("width","400px"),pile=[],redoPile(),cpuTurn()):(makeCard(pile,"cpuhand","facedown"),cpuHand=cpuHand.concat(pile),pile=[],redoPile(),$("#cpuMove").text("CPU picked up the pile"),playerTurn())}function redoPile(){$("#pile").empty();0<pile.length&&makeCard([pile[pile.length-1]],"pile")}
var getRandomCard=function(){return Math.floor(52*Math.random()+1)},shuffleDeck=function(){for(var a=[],b=0;52!=a.length;){var d=getRandomCard();-1===a.indexOf(d)&&(a[b]=d,b++)}return a},makeCard=function(a,b,d){for(var c=0;c<a.length;c++){div=document.getElementById(b);var e=document.createElement("DIV"),f=document.createElement("P"),k=document.createTextNode(a[c]),g=document.createElement("IMG"),h=document.createElement("IMG");f.appendChild(k);e.appendChild(g);e.appendChild(f);e.appendChild(h);
div.appendChild(e);$(e).addClass("card");"undefined"!==typeof d&&$(g).addClass("facedown");$(h).attr("src","classic-cards/card_back.png");$(h).css({width:"80px",height:"100px",zIndex:"1",position:"absolute"});e="classic-cards/"+a[c]+".png";$(g).attr("src",e);$(g).css({width:"80px",height:"100px",zIndex:"2",position:"absolute"})}},getCardValue=function(a){a=Math.ceil(a/4);switch(a){case 1:a="A";break;case 11:a="J";break;case 12:a="Q";break;case 13:a="K";break;default:a=a.toString()}return a},getCardNumValue=
function(a){switch(a){case "A":return 14;case "K":return 13;case "Q":return 12;case "J":return 11;default:return parseInt(a)}},removeCard=function(a,b,d){d=a.indexOf(d);a.splice(d,1);$("#"+b+" img:first-child").hasClass("facedown")?($("#"+b).empty(),makeCard(a,b,"facedown")):($("#"+b).empty(),makeCard(a,b))},compareCards=function(a,b,d){a=getCardValue(a);b=getCardValue(b);if(a===b)return 0;if("2"===a||"7"===a||"10"===a)return 1;if("undefined"===typeof d)return getCardNumValue(a)>getCardNumValue(b)?
1:-1;if("SEVEN"===d)return 7>getCardNumValue(a)?1:-1;if("cpuAI"===d)return"2"===b||"7"===b||"10"===a?-1:getCardNumValue(a)>getCardNumValue(b)?1:-1};function loseScreen(){$("#lose").fadeIn("500");$("#playagain").fadeIn("500");$("#playagain").click(initializeGame)}function winScreen(){$("#win").fadeIn("500");$("#playagain").fadeIn("500");$("#playagain").click(initializeGame)}
function resetAll(){deck=shuffleDeck();cpuFacedown=[];playerFacedown=[];cpuHand=[];playerHand=[];playerFaceup=[];cpuFaceup=[];pile=[];$("*").off();$(".cardholder").empty();$("#bomb").css("visibility","hidden");$("#cpumove").text("");$("#chooseThree").fadeIn("500");$("#startGame").fadeIn("500");$(".start").css("display","none");$("#playerhand").css("width","300");$("#lose").fadeOut("500");$("#win").fadeOut("500");$("#playagain").fadeOut("500");$("#playerflipped").fadeOut()};
